name: candle
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  google_fonts: ^2.2.0
  auto_size_text_field: ^0.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_datetime_picker: ^1.5.0
  firebase_auth: ^3.3.6
  firebase_core: ^1.10.0
  cloud_firestore: ^3.1.7
  get: ^4.6.1
  time_machine: ^0.9.16
  shared_preferences: ^2.0.12
  fluttertoast: ^7.1.8
  loading_animations: ^2.1.0
  flutter_email_sender: ^5.0.2
  file_picker: ^4.3.3
  firebase_storage: ^10.2.6
  uuid: ^3.0.5
  mailer: ^5.1.0
  flutter_tags: ^0.4.9
  email_validator: ^1.0.6
  audioplayers: ^0.20.1
  another_flushbar: ^1.10.24
  simple_animations: ^1.3.3
  flutter_custom_clippers: ^1.1.2
  square_in_app_payments: ^1.7.2
  google_sign_in: ^5.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.17.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/Icons/Icon_96x96.jpg"
  image_path_android: "assets/images/Icons/Icon_96x96.jpg"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true



  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/_Common/BGs/Bg.jpg
    - assets/images/_Common/Candle/Globe/Earth_00084.png
    - assets/images/_Common/Candle/Fire/Light_1_00000.png
    - assets/images/_Common/Candle/Globe/
    - assets/images/_Common/Candle/Fire/
    - assets/images/_Common/Candle/GlobeSpinAnim/
    - assets/images/_Common/Candle/
    - assets/images/_Common/UIElements/
    - assets/images/CandleTypes/
    - assets/images/_Common/Icons/
    - assets/images/fireSpreadsheet.png
    - assets/fires.gif
    - assets/images/_Common/Candle/GlobeSpinAnim/GlobeSpin01.gif
    - assets/images/_Common/Candle/GlobeSpinAnim/GlobeSpin02.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
